package com.example.vizi.ai;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.atomic.AtomicReference;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:vizi_ai_rewrite_test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
@AutoConfigureMockMvc
@ActiveProfiles("test")
class AiTextRewriteApiIntegrationTests {

    private static final String CANVAS = """
            {"layers":[{"type":"text","text":"Vizi Atelier","x":10,"y":10,"width":45,"height":12}]}
            """;
    private static final AtomicReference<String> GEMINI_RESPONSE = new AtomicReference<>();
    private static final AtomicReference<String> GEMINI_REQUEST = new AtomicReference<>();
    private static final HttpServer GEMINI_SERVER = startGeminiServer();

    @Autowired
    MockMvc mockMvc;

    @Autowired
    JdbcTemplate jdbcTemplate;

    @DynamicPropertySource
    static void geminiProperties(DynamicPropertyRegistry registry) {
        registry.add("app.ai.gemini.api-key", () -> "test-api-key");
        registry.add("app.ai.gemini.text-model", () -> "gemini-test");
        registry.add("app.ai.gemini.base-url", () -> "http://127.0.0.1:" + GEMINI_SERVER.getAddress().getPort());
    }

    @AfterAll
    static void stopGeminiServer() {
        GEMINI_SERVER.stop(0);
    }

    @BeforeEach
    void resetDatabase() {
        jdbcTemplate.execute("""
                create table if not exists users (
                    id bigint generated by default as identity primary key,
                    email varchar(320) not null unique,
                    password_hash varchar(255) not null,
                    full_name varchar(160) not null,
                    phone varchar(40),
                    address varchar(500),
                    role varchar(32) not null,
                    created_at timestamp with time zone not null default current_timestamp,
                    updated_at timestamp with time zone not null default current_timestamp
                )
                """);
        jdbcTemplate.execute("""
                create table if not exists designs (
                    id bigint primary key,
                    user_id bigint not null,
                    template_id bigint,
                    name varchar(160) not null,
                    canvas_json varchar not null,
                    front_preview_url varchar(2048),
                    back_preview_url varchar(2048),
                    width_mm numeric(8,2) not null,
                    height_mm numeric(8,2) not null,
                    created_at timestamp with time zone not null default current_timestamp,
                    updated_at timestamp with time zone not null default current_timestamp
                )
                """);
        jdbcTemplate.execute("""
                create table if not exists ai_usage_logs (
                    id bigint generated by default as identity primary key,
                    feature varchar(80) not null,
                    model varchar(120) not null,
                    status varchar(16) not null,
                    latency_ms bigint not null,
                    error_code varchar(64),
                    created_at timestamp with time zone not null default current_timestamp
                )
                """);
        jdbcTemplate.update("delete from ai_usage_logs");
        jdbcTemplate.update("delete from designs");
        jdbcTemplate.update("delete from users");
        jdbcTemplate.update("insert into users (id, email, password_hash, full_name, role) values (1, 'owner@example.test', 'hash', 'Owner', 'USER')");
        jdbcTemplate.update("insert into users (id, email, password_hash, full_name, role) values (2, 'other@example.test', 'hash', 'Other', 'USER')");
        jdbcTemplate.update("""
                insert into designs (id, user_id, name, canvas_json, width_mm, height_mm)
                values (10, 1, 'Luxury Card', ?, 90.00, 54.00)
                """, CANVAS);
        GEMINI_REQUEST.set(null);
    }

    @Test
    void ownerReceivesPreviewPatchAndSavedCanvasRemainsUntouched() throws Exception {
        respondWithPatch("""
                {"schemaVersion":1,"editStrength":"light","targetSide":"front","summary":"Refined headline","actions":[{"op":"update_text","layerId":"layer-1","text":"Vizi Luxury Atelier"}]}
                """);

        mockMvc.perform(rewriteRequest().with(user("owner@example.test")).with(csrf()))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.schemaVersion").value(1))
                .andExpect(jsonPath("$.editStrength").value("light"))
                .andExpect(jsonPath("$.targetSide").value("front"))
                .andExpect(jsonPath("$.actions.length()").value(1))
                .andExpect(jsonPath("$.actions[0].op").value("update_text"))
                .andExpect(jsonPath("$.actions[0].layerId").value("layer-1"))
                .andExpect(jsonPath("$.actions[0].text").value("Vizi Luxury Atelier"));

        assertThat(jdbcTemplate.queryForObject("select canvas_json from designs where id = 10", String.class))
                .isEqualTo(CANVAS);
        assertThat(jdbcTemplate.queryForObject("select feature from ai_usage_logs", String.class))
                .isEqualTo("text.rewrite");
        assertThat(GEMINI_REQUEST.get()).contains("Vizi Atelier").contains("Make this more luxurious");
    }

    @Test
    void missingCsrfIsRejectedBeforeCallingGemini() throws Exception {
        respondWithPatch("""
                {"schemaVersion":1,"editStrength":"light","targetSide":"front","summary":"Refined","actions":[{"op":"update_text","layerId":"layer-1","text":"Vizi Luxury Atelier"}]}
                """);

        mockMvc.perform(rewriteRequest().with(user("owner@example.test")))
                .andExpect(status().isForbidden());

        assertThat(GEMINI_REQUEST.get()).isNull();
    }

    @Test
    void anotherUserCannotRewriteAnOwnersDesign() throws Exception {
        mockMvc.perform(rewriteRequest().with(user("other@example.test")).with(csrf()))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.message").value("Design not found"));

        assertThat(GEMINI_REQUEST.get()).isNull();
    }

    @Test
    void modelPatchOutsideTextRewriteContractIsRejected() throws Exception {
        respondWithPatch("""
                {"schemaVersion":1,"editStrength":"light","targetSide":"front","summary":"Changed color","actions":[{"op":"update_fill","layerId":"layer-1","fill":"#1F2937"}]}
                """);

        mockMvc.perform(rewriteRequest().with(user("owner@example.test")).with(csrf()))
                .andExpect(status().isBadGateway())
                .andExpect(jsonPath("$.message").value("Gemini response did not produce a valid text rewrite"));
    }

    private static org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder rewriteRequest() {
        return post("/api/ai/text/rewrite")
                .contentType(MediaType.APPLICATION_JSON)
                .content("""
                        {
                          "designId": 10,
                          "layerId": "layer-1",
                          "prompt": "Make this more luxurious",
                          "editStrength": "light",
                          "targetSide": "front"
                        }
                        """);
    }

    private static void respondWithPatch(String patch) {
        GEMINI_RESPONSE.set("""
                {"candidates":[{"content":{"parts":[{"text":%s}]}}]}
                """.formatted(jsonString(patch)));
    }

    private static String jsonString(String value) {
        return '"' + value.replace("\\", "\\\\").replace("\"", "\\\"")
                .replace("\n", "\\n").replace("\r", "\\r") + '"';
    }

    private static HttpServer startGeminiServer() {
        try {
            var server = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
            server.createContext("/", exchange -> {
                GEMINI_REQUEST.set(new String(exchange.getRequestBody().readAllBytes(), StandardCharsets.UTF_8));
                var response = GEMINI_RESPONSE.get().getBytes(StandardCharsets.UTF_8);
                exchange.getResponseHeaders().set("Content-Type", "application/json");
                exchange.sendResponseHeaders(200, response.length);
                try (var body = exchange.getResponseBody()) {
                    body.write(response);
                }
            });
            server.start();
            return server;
        } catch (IOException exception) {
            throw new IllegalStateException("Could not start fake Gemini server", exception);
        }
    }
}