package com.example.vizi.ai;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.Set;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;

@SpringBootTest
@ActiveProfiles("test")
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:h2:mem:vizi_ai_usage_test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
class AiUsageLogServiceTests {

    @Autowired
    AiUsageLogService service;

    @Autowired
    JdbcTemplate jdbcTemplate;

    @BeforeEach
    void resetDatabase() {
        jdbcTemplate.execute("""
                create table if not exists ai_usage_logs (
                    id bigint generated by default as identity primary key,
                    feature varchar(80) not null,
                    model varchar(120) not null,
                    status varchar(16) not null,
                    latency_ms bigint not null,
                    error_code varchar(64),
                    created_at timestamp with time zone not null default current_timestamp
                )
                """);
        jdbcTemplate.update("delete from ai_usage_logs");
    }

    @Test
    void recordsOnlyOperationalMetadata() {
        service.record("text.generate", "gemini-test", "SUCCESS", 17, null);

        var row = jdbcTemplate.queryForMap("""
                select feature, model, status, latency_ms, error_code, created_at
                from ai_usage_logs
                """);
        assertThat(row)
                .containsEntry("feature", "text.generate")
                .containsEntry("model", "gemini-test")
                .containsEntry("status", "SUCCESS")
                .containsEntry("latency_ms", 17L)
                .containsEntry("error_code", null);
        assertThat(row.get("created_at")).isNotNull();

        var columns = Set.copyOf(jdbcTemplate.queryForList("""
                select column_name
                from information_schema.columns
                where table_name = 'ai_usage_logs'
                """, String.class));
        assertThat(columns)
                .contains("feature", "model", "status", "latency_ms", "error_code", "created_at")
                .doesNotContain("prompt", "response", "api_key", "secret");
    }
}
