create table users (
    id bigint generated by default as identity primary key,
    email varchar(320) not null unique,
    password_hash varchar(255),
    full_name varchar(160) not null,
    role varchar(32) not null default 'USER',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint users_role_check check (role in ('USER', 'ADMIN'))
);

create table templates (
    id bigint generated by default as identity primary key,
    name varchar(160) not null,
    category varchar(80) not null,
    preview_url varchar(2048),
    width_mm numeric(8,2) not null,
    height_mm numeric(8,2) not null,
    canvas_json jsonb not null,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    constraint templates_size_check check (width_mm > 0 and height_mm > 0)
);

create table designs (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    template_id bigint references templates(id),
    name varchar(160) not null,
    canvas_json jsonb not null,
    front_preview_url varchar(2048),
    back_preview_url varchar(2048),
    width_mm numeric(8,2) not null,
    height_mm numeric(8,2) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint designs_size_check check (width_mm > 0 and height_mm > 0)
);

create table design_snapshots (
    id bigint generated by default as identity primary key,
    design_id bigint not null references designs(id) on delete cascade,
    user_id bigint not null references users(id),
    reason varchar(64) not null,
    canvas_json jsonb not null,
    created_at timestamptz not null default now()
);

create table assets (
    id bigint generated by default as identity primary key,
    user_id bigint references users(id),
    type varchar(32) not null,
    file_url varchar(2048) not null,
    file_name varchar(255) not null,
    mime_type varchar(120) not null,
    size_bytes bigint not null,
    width_px integer,
    height_px integer,
    created_at timestamptz not null default now(),
    constraint assets_type_check check (type in ('image', 'icon', 'shape')),
    constraint assets_size_check check (size_bytes >= 0),
    constraint assets_dimensions_check check (
        (width_px is null or width_px > 0)
        and (height_px is null or height_px > 0)
    )
);

create table orders (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    status varchar(40) not null default 'DRAFT',
    total_amount numeric(12,2) not null default 0,
    customer_note text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint orders_status_check check (
        status in ('DRAFT', 'PENDING_PAYMENT', 'PAID', 'PRINTING', 'DONE', 'CANCELLED')
    ),
    constraint orders_total_amount_check check (total_amount >= 0)
);

create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references orders(id) on delete cascade,
    design_id bigint not null references designs(id),
    design_snapshot_json jsonb not null,
    print_config_json jsonb not null,
    quantity integer not null,
    unit_price numeric(12,2) not null,
    subtotal numeric(12,2) not null,
    constraint order_items_quantity_check check (quantity > 0),
    constraint order_items_price_check check (unit_price >= 0 and subtotal >= 0)
);

create index idx_designs_user_id on designs(user_id);
create index idx_designs_template_id on designs(template_id);
create index idx_design_snapshots_design_id on design_snapshots(design_id);
create index idx_design_snapshots_user_id on design_snapshots(user_id);
create index idx_assets_user_id on assets(user_id);
create index idx_orders_user_id on orders(user_id);
create index idx_order_items_order_id on order_items(order_id);
create index idx_order_items_design_id on order_items(design_id);
create index idx_templates_active_category on templates(active, category);
