create table ai_usage_logs (
    id bigint generated by default as identity primary key,
    user_id bigint references users(id) on delete set null,
    feature varchar(80) not null,
    model varchar(120) not null,
    status varchar(16) not null,
    latency_ms bigint not null,
    error_code varchar(64),
    created_at timestamptz not null default now(),
    constraint ai_usage_logs_status_check check (status in ('SUCCESS', 'FAILED')),
    constraint ai_usage_logs_latency_check check (latency_ms >= 0)
);

create index idx_ai_usage_logs_user_id on ai_usage_logs(user_id);
create index idx_ai_usage_logs_created_at on ai_usage_logs(created_at);
