-- Replace Geo Red Corporate Card full-card image layers with editable rect/text canvas.
-- Targets by name or id so it is safe on DBs where the row id is not 45.

UPDATE templates
SET preview_url = NULL,
    canvas_json = $${
  "version": 1,
  "selectedSide": "front",
  "sides": ["front", "back"],
  "layers": [
    {
      "id": "front-bg",
      "type": "rect",
      "name": "Background",
      "page": "front",
      "x": 0,
      "y": 0,
      "width": 100,
      "height": 100,
      "fill": "#FAFAFA",
      "stroke": "transparent",
      "strokeWidth": 0,
      "radius": 0,
      "opacity": 1
    },
    {
      "id": "front-red-panel",
      "type": "rect",
      "name": "Red panel",
      "page": "front",
      "x": 0,
      "y": 0,
      "width": 29,
      "height": 100,
      "fill": "#B4282A",
      "stroke": "transparent",
      "strokeWidth": 0,
      "radius": 0,
      "opacity": 1
    },
    {
      "id": "front-red-dark",
      "type": "rect",
      "name": "Red facet dark",
      "page": "front",
      "x": 0,
      "y": 0,
      "width": 18,
      "height": 42,
      "fill": "#8E121C",
      "stroke": "transparent",
      "strokeWidth": 0,
      "radius": 0,
      "opacity": 0.85
    },
    {
      "id": "front-red-mid",
      "type": "rect",
      "name": "Red facet mid",
      "page": "front",
      "x": 10,
      "y": 28,
      "width": 16,
      "height": 38,
      "fill": "#C43C38",
      "stroke": "transparent",
      "strokeWidth": 0,
      "radius": 0,
      "opacity": 0.75
    },
    {
      "id": "front-red-hi",
      "type": "rect",
      "name": "Red facet light",
      "page": "front",
      "x": 4,
      "y": 58,
      "width": 20,
      "height": 32,
      "fill": "#D4554F",
      "stroke": "transparent",
      "strokeWidth": 0,
      "radius": 0,
      "opacity": 0.55
    },
    {
      "id": "front-logo",
      "type": "icon",
      "name": "Logo mark",
      "page": "front",
      "x": 52,
      "y": 20,
      "width": 14,
      "height": 18,
      "text": "⬡",
      "color": "#9B1A22",
      "fontSize": 32,
      "fontWeight": 400,
      "opacity": 1
    },
    {
      "id": "front-company",
      "type": "text",
      "name": "Company name",
      "page": "front",
      "x": 36,
      "y": 48,
      "width": 52,
      "height": 12,
      "text": "COMPANY NAME",
      "color": "#9B1A22",
      "fontSize": 15,
      "fontWeight": 700,
      "fontFamily": "system-ui, Segoe UI, Arial, sans-serif",
      "opacity": 1
    },
    {
      "id": "front-tagline",
      "type": "text",
      "name": "Tagline",
      "page": "front",
      "x": 36,
      "y": 60,
      "width": 52,
      "height": 8,
      "text": "TAGLINE GOES HERE",
      "color": "#9B1A22",
      "fontSize": 8,
      "fontWeight": 500,
      "fontFamily": "system-ui, Segoe UI, Arial, sans-serif",
      "opacity": 0.88
    },
    {
      "id": "back-bg",
      "type": "rect",
      "name": "Background",
      "page": "back",
      "x": 0,
      "y": 0,
      "width": 100,
      "height": 100,
      "fill": "#FAFAFA",
      "stroke": "transparent",
      "strokeWidth": 0,
      "radius": 0,
      "opacity": 1
    },
    {
      "id": "back-red-panel",
      "type": "rect",
      "name": "Red panel",
      "page": "back",
      "x": 44,
      "y": 0,
      "width": 56,
      "height": 100,
      "fill": "#B0282C",
      "stroke": "transparent",
      "strokeWidth": 0,
      "radius": 0,
      "opacity": 1
    },
    {
      "id": "back-red-dark",
      "type": "rect",
      "name": "Red facet",
      "page": "back",
      "x": 52,
      "y": 0,
      "width": 48,
      "height": 38,
      "fill": "#8A121C",
      "stroke": "transparent",
      "strokeWidth": 0,
      "radius": 0,
      "opacity": 0.45
    },
    {
      "id": "back-company",
      "type": "text",
      "name": "Company",
      "page": "back",
      "x": 8,
      "y": 8,
      "width": 32,
      "height": 8,
      "text": "COMPANY NAME",
      "color": "#9B1A22",
      "fontSize": 8,
      "fontWeight": 700,
      "fontFamily": "system-ui, Segoe UI, Arial, sans-serif",
      "opacity": 1
    },
    {
      "id": "back-tagline",
      "type": "text",
      "name": "Tagline",
      "page": "back",
      "x": 8,
      "y": 15,
      "width": 32,
      "height": 6,
      "text": "TAGLINE GOES HERE",
      "color": "#9B1A22",
      "fontSize": 6,
      "fontWeight": 500,
      "fontFamily": "system-ui, Segoe UI, Arial, sans-serif",
      "opacity": 0.82
    },
    {
      "id": "back-address",
      "type": "text",
      "name": "Address",
      "page": "back",
      "x": 8,
      "y": 28,
      "width": 34,
      "height": 14,
      "text": "YOUR FIRST ADDRESS LINE\nYOUR SECOND ADDRESS LINE",
      "color": "#9B1A22",
      "fontSize": 7,
      "fontWeight": 600,
      "fontFamily": "system-ui, Segoe UI, Arial, sans-serif",
      "opacity": 1
    },
    {
      "id": "back-email",
      "type": "text",
      "name": "Email",
      "page": "back",
      "x": 8,
      "y": 46,
      "width": 34,
      "height": 8,
      "text": "JOHN.SMITH@YOURMAIL.COM",
      "color": "#9B1A22",
      "fontSize": 7,
      "fontWeight": 600,
      "fontFamily": "system-ui, Segoe UI, Arial, sans-serif",
      "opacity": 1
    },
    {
      "id": "back-phone",
      "type": "text",
      "name": "Phone",
      "page": "back",
      "x": 8,
      "y": 56,
      "width": 34,
      "height": 12,
      "text": "+0 123 456 789\n+0 987 654 321",
      "color": "#9B1A22",
      "fontSize": 7,
      "fontWeight": 600,
      "fontFamily": "system-ui, Segoe UI, Arial, sans-serif",
      "opacity": 1
    },
    {
      "id": "back-web",
      "type": "text",
      "name": "Website",
      "page": "back",
      "x": 8,
      "y": 72,
      "width": 34,
      "height": 8,
      "text": "WWW.YOURCOMPANY.COM",
      "color": "#9B1A22",
      "fontSize": 7,
      "fontWeight": 600,
      "fontFamily": "system-ui, Segoe UI, Arial, sans-serif",
      "opacity": 1
    },
    {
      "id": "back-person",
      "type": "text",
      "name": "Person name",
      "page": "back",
      "x": 48,
      "y": 20,
      "width": 48,
      "height": 12,
      "text": "ALEXANDER. W",
      "color": "#FFFFFF",
      "fontSize": 14,
      "fontWeight": 700,
      "fontFamily": "system-ui, Segoe UI, Arial, sans-serif",
      "opacity": 1
    },
    {
      "id": "back-role",
      "type": "text",
      "name": "Role",
      "page": "back",
      "x": 48,
      "y": 32,
      "width": 48,
      "height": 8,
      "text": "HEAD OF ENGINEER",
      "color": "#FFFFFF",
      "fontSize": 8,
      "fontWeight": 500,
      "fontFamily": "system-ui, Segoe UI, Arial, sans-serif",
      "opacity": 0.93
    },
    {
      "id": "back-qr",
      "type": "rect",
      "name": "QR block",
      "page": "back",
      "x": 58,
      "y": 52,
      "width": 28,
      "height": 36,
      "fill": "#FFFFFF",
      "stroke": "#A01C26",
      "strokeWidth": 1,
      "radius": 2,
      "opacity": 1
    },
    {
      "id": "back-qr-mark",
      "type": "text",
      "name": "QR label",
      "page": "back",
      "x": 60,
      "y": 64,
      "width": 24,
      "height": 10,
      "text": "QR",
      "color": "#A01C26",
      "fontSize": 14,
      "fontWeight": 800,
      "fontFamily": "system-ui, Segoe UI, Arial, sans-serif",
      "opacity": 1
    }
  ]
}$$::jsonb
WHERE name = 'Geo Red Corporate Card'
   OR id = 45;
