create table paper_stocks (
    id bigint generated by default as identity primary key,
    code varchar(64) not null unique,
    name varchar(160) not null,
    description varchar(500),
    gsm integer,
    price_per_100 numeric(12,2) not null,
    status varchar(32) not null default 'IN_STOCK',
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint paper_stocks_code_check check (code ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    constraint paper_stocks_gsm_check check (gsm is null or gsm > 0),
    constraint paper_stocks_price_check check (price_per_100 >= 0),
    constraint paper_stocks_status_check check (status in ('IN_STOCK', 'OUT_OF_STOCK'))
);

create index idx_paper_stocks_active_status on paper_stocks(active, status);

insert into paper_stocks(code, name, description, gsm, price_per_100, status, active) values
    ('matte-350', 'Couche 350gsm', 'Smooth coated paper for sharp colours and clean text.', 350, 180000, 'IN_STOCK', true),
    ('silk-400', 'Bristol 400gsm', 'Thick rigid stock for premium business cards.', 400, 240000, 'IN_STOCK', true),
    ('linen-300', 'Ivory 300gsm', 'Firm stock with a smooth printable face.', 300, 280000, 'IN_STOCK', true),
    ('ford-250', 'Ford 250gsm', 'Uncoated paper that is easy to write on.', 250, 170000, 'IN_STOCK', true),
    ('kraft-300', 'Kraft 300gsm', 'Recycled brown stock with a natural finish.', 300, 230000, 'IN_STOCK', true),
    ('fine-art-300', 'Fine art 300gsm', 'Textured premium paper for special finishes.', 300, 320000, 'IN_STOCK', true),
    ('plastic-250', 'Plastic 250 micron', 'Water-resistant and tear-resistant card stock.', null, 450000, 'IN_STOCK', true);