export type StockKind = "photo" | "illustration" | "background";

export type StockAsset = {
  id: string;
  title: string;
  kind: StockKind;
  collection: string;
  previewUrl: string;
  sourceUrl: string;
  tags: string[];
  credit: string;
};

// Starter catalog used when the remote stock provider is unavailable.
export const stockAssets: StockAsset[] = [
  {
    id: "photo-studio-lights",
    title: "Studio lights",
    kind: "photo",
    collection: "Trending",
    previewUrl: "https://picsum.photos/id/0/640/480",
    sourceUrl: "https://picsum.photos/",
    tags: ["studio", "desk", "technology"],
    credit: "Demo photo catalog",
  },
  {
    id: "photo-mountain-road",
    title: "Mountain road",
    kind: "photo",
    collection: "Nature",
    previewUrl: "https://picsum.photos/id/10/640/480",
    sourceUrl: "https://picsum.photos/",
    tags: ["mountain", "road", "landscape"],
    credit: "Demo photo catalog",
  },
  {
    id: "photo-lake",
    title: "Blue lake",
    kind: "photo",
    collection: "Nature",
    previewUrl: "https://picsum.photos/id/14/640/480",
    sourceUrl: "https://picsum.photos/",
    tags: ["lake", "water", "landscape"],
    credit: "Demo photo catalog",
  },
  {
    id: "photo-forest",
    title: "Forest trail",
    kind: "photo",
    collection: "Nature",
    previewUrl: "https://picsum.photos/id/15/640/480",
    sourceUrl: "https://picsum.photos/",
    tags: ["forest", "trees", "green"],
    credit: "Demo photo catalog",
  },
  {
    id: "photo-architecture",
    title: "Modern architecture",
    kind: "photo",
    collection: "Commerce",
    previewUrl: "https://picsum.photos/id/16/640/480",
    sourceUrl: "https://picsum.photos/",
    tags: ["building", "architecture", "business"],
    credit: "Demo photo catalog",
  },
  {
    id: "photo-coast",
    title: "Quiet coast",
    kind: "photo",
    collection: "Backgrounds",
    previewUrl: "https://picsum.photos/id/24/640/480",
    sourceUrl: "https://picsum.photos/",
    tags: ["coast", "sea", "blue"],
    credit: "Demo photo catalog",
  },
  {
    id: "photo-city",
    title: "City detail",
    kind: "photo",
    collection: "Trending",
    previewUrl: "https://picsum.photos/id/25/640/480",
    sourceUrl: "https://picsum.photos/",
    tags: ["city", "street", "urban"],
    credit: "Demo photo catalog",
  },
  {
    id: "photo-bridge",
    title: "Bridge lines",
    kind: "photo",
    collection: "Backgrounds",
    previewUrl: "https://picsum.photos/id/29/640/480",
    sourceUrl: "https://picsum.photos/",
    tags: ["bridge", "lines", "structure"],
    credit: "Demo photo catalog",
  },
  {
    id: "photo-waterfall",
    title: "Waterfall",
    kind: "photo",
    collection: "Nature",
    previewUrl: "https://picsum.photos/id/30/640/480",
    sourceUrl: "https://picsum.photos/",
    tags: ["waterfall", "nature", "water"],
    credit: "Demo photo catalog",
  },
  {
    id: "photo-hills",
    title: "Green hills",
    kind: "photo",
    collection: "Nature",
    previewUrl: "https://picsum.photos/id/39/640/480",
    sourceUrl: "https://picsum.photos/",
    tags: ["hills", "green", "travel"],
    credit: "Demo photo catalog",
  },
  {
    id: "photo-road",
    title: "Open road",
    kind: "photo",
    collection: "Travel",
    previewUrl: "https://picsum.photos/id/48/640/480",
    sourceUrl: "https://picsum.photos/",
    tags: ["road", "travel", "journey"],
    credit: "Demo photo catalog",
  },
  {
    id: "photo-workspace",
    title: "Creative workspace",
    kind: "photo",
    collection: "Media",
    previewUrl: "https://picsum.photos/id/60/640/480",
    sourceUrl: "https://picsum.photos/",
    tags: ["workspace", "creative", "office"],
    credit: "Demo photo catalog",
  },
  {
    id: "background-sunset",
    title: "Warm horizon",
    kind: "background",
    collection: "Backgrounds",
    previewUrl: "https://picsum.photos/id/96/640/480",
    sourceUrl: "https://picsum.photos/",
    tags: ["sunset", "warm", "background"],
    credit: "Demo photo catalog",
  },
  {
    id: "background-minimal",
    title: "Minimal wall",
    kind: "background",
    collection: "Backgrounds",
    previewUrl: "https://picsum.photos/id/111/640/480",
    sourceUrl: "https://picsum.photos/",
    tags: ["minimal", "wall", "neutral"],
    credit: "Demo photo catalog",
  },
  {
    id: "illustration-blue",
    title: "Blue shapes",
    kind: "illustration",
    collection: "Illustrations",
    previewUrl: "https://api.dicebear.com/9.x/shapes/png?seed=vizi-blue&size=640&backgroundColor=ffffff",
    sourceUrl: "https://www.dicebear.com/",
    tags: ["shapes", "blue", "abstract"],
    credit: "DiceBear",
  },
  {
    id: "illustration-coral",
    title: "Coral shapes",
    kind: "illustration",
    collection: "Illustrations",
    previewUrl: "https://api.dicebear.com/9.x/shapes/png?seed=vizi-coral&size=640&backgroundColor=fff5f8",
    sourceUrl: "https://www.dicebear.com/",
    tags: ["shapes", "coral", "abstract"],
    credit: "DiceBear",
  },
  {
    id: "illustration-forest",
    title: "Forest shapes",
    kind: "illustration",
    collection: "Illustrations",
    previewUrl: "https://api.dicebear.com/9.x/shapes/png?seed=vizi-forest&size=640&backgroundColor=effaf4",
    sourceUrl: "https://www.dicebear.com/",
    tags: ["shapes", "forest", "green"],
    credit: "DiceBear",
  },
];
