package com.example.vizi.auth;

import static org.hamcrest.Matchers.not;
import static org.hamcrest.Matchers.containsString;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.mock.web.MockHttpSession;
import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:vizi_auth_test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password="
})
@AutoConfigureMockMvc
@ActiveProfiles("test")
@Sql(statements = {
        "create table if not exists users (id bigint generated by default as identity primary key, email varchar(320) not null unique, password_hash varchar(255), full_name varchar(160) not null, role varchar(32) not null default 'USER', created_at timestamp with time zone not null default current_timestamp, updated_at timestamp with time zone not null default current_timestamp)",
        "delete from users"
})
class AuthApiIntegrationTests {

    @Autowired
    MockMvc mockMvc;

    @Test
    void registrationWithoutCsrfIsRejected() throws Exception {
        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "email": "customer@example.test",
                                  "password": "StrongPass123",
                                  "fullName": "Test Customer"
                                }
                                """))
                .andExpect(status().isForbidden());
    }

    @Test
    void validRegistrationCreatesAccountWithoutExposingPassword() throws Exception {
        mockMvc.perform(post("/api/auth/register")
                        .with(csrf())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "email": "Customer@Example.Test",
                                  "password": "StrongPass123",
                                  "fullName": "Test Customer"
                                }
                                """))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.email").value("customer@example.test"))
                .andExpect(jsonPath("$.fullName").value("Test Customer"))
                .andExpect(content().string(not(containsString("StrongPass123"))))
                .andExpect(content().string(not(containsString("passwordHash"))));
    }

    @Test
    void invalidRegistrationIsRejectedAsBadRequest() throws Exception {
        mockMvc.perform(post("/api/auth/register")
                        .with(csrf())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "email": "not-an-email",
                                  "password": "short",
                                  "fullName": "Test Customer"
                                }
                                """))
                .andExpect(status().isBadRequest())
                .andExpect(content().string(not(containsString("short"))));
    }

    @Test
    void malformedRegistrationJsonIsRejectedAsBadRequest() throws Exception {
        mockMvc.perform(post("/api/auth/register")
                        .with(csrf())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"email\":"))
                .andExpect(status().isBadRequest());
    }

    @Test
    void duplicateEmailIsRejectedCaseInsensitively() throws Exception {
        register("customer@example.test", "StrongPass123");

        mockMvc.perform(post("/api/auth/register")
                        .with(csrf())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "email": "CUSTOMER@example.test",
                                  "password": "AnotherPass123",
                                  "fullName": "Other Customer"
                                }
                                """))
                .andExpect(status().isConflict())
                .andExpect(jsonPath("$.message").value("Email already registered"));
    }

    @Test
    void loginCreatesSessionThatCanReadCurrentUser() throws Exception {
        register("customer@example.test", "StrongPass123");

        var login = mockMvc.perform(post("/api/auth/login")
                        .with(csrf())
                        .param("email", "customer@example.test")
                        .param("password", "StrongPass123"))
                .andExpect(status().isNoContent())
                .andReturn();
        var session = (MockHttpSession) login.getRequest().getSession(false);

        mockMvc.perform(get("/api/auth/me").session(session))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.email").value("customer@example.test"))
                .andExpect(jsonPath("$.role").value("USER"));
    }

    @Test
    void wrongPasswordAndAnonymousCurrentUserAreUnauthorized() throws Exception {
        register("customer@example.test", "StrongPass123");

        mockMvc.perform(post("/api/auth/login")
                        .with(csrf())
                        .param("email", "customer@example.test")
                        .param("password", "WrongPass123"))
                .andExpect(status().isUnauthorized());

        mockMvc.perform(get("/api/auth/me"))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void csrfEndpointIssuesSessionToken() throws Exception {
        mockMvc.perform(get("/api/auth/csrf"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.headerName").value("X-CSRF-TOKEN"))
                .andExpect(jsonPath("$.token").isNotEmpty());
    }

    @Test
    void logoutInvalidatesAuthenticatedSession() throws Exception {
        register("customer@example.test", "StrongPass123");
        var login = mockMvc.perform(post("/api/auth/login")
                        .with(csrf())
                        .param("email", "customer@example.test")
                        .param("password", "StrongPass123"))
                .andExpect(status().isNoContent())
                .andReturn();
        var session = (MockHttpSession) login.getRequest().getSession(false);

        mockMvc.perform(post("/api/auth/logout").with(csrf()).session(session))
                .andExpect(status().isNoContent());

        mockMvc.perform(get("/api/auth/me").session(session))
                .andExpect(status().isUnauthorized());
    }

    private void register(String email, String password) throws Exception {
        mockMvc.perform(post("/api/auth/register")
                        .with(csrf())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "email": "%s",
                                  "password": "%s",
                                  "fullName": "Test Customer"
                                }
                                """.formatted(email, password)))
                .andExpect(status().isCreated());
    }
}
